name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Установка зависимостей
        run: npm install

      - name: Тестирование
        run: npm test

      - name: Логин в DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Сборка Docker-образа
        run: docker build -t your-dockerhub-user/your-image-name:latest .

      - name: Push Docker-образа
        run: docker push your-dockerhub-user/your-image-name:latest
